liip_imagine:
    driver: "imagick"

    resolvers:
        default:
            web_path: ~

    twig:
        mode: lazy

    filter_sets:
        cache: ~

        my_thumb_small:
            quality: 80
            filters:
                relative_resize:
                    heighten: 200
                watermark_image:
                    image: assets/images/mark.webp
                    size: 0.2
                    position: bottomright

        my_thumb_big:
            quality: 80
            filters:
                relative_resize:
                    heighten: 400
                watermark_image:
                    image: assets/images/mark.webp
                    size: 0.2
                    position: bottomright