services:
    db:
        image: mysql:8.0
        container_name: db_container
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: 'Store'
            MYSQL_USER: 'timur'
            MYSQL_PASSWORD: 'admin'
            MYSQL_ROOT_PASSWORD: 'admin'
        ports:
            - '3306:3306'
        networks:
            - market

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq_container
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/data
        networks:
            - market

    web:
        build: .
        container_name: web_container
        ports:
            - "8741:80"
        restart: always
        depends_on:
            - db
            - rabbitmq
        networks:
            - market

networks:
    market:

volumes:
    db-data:
    rabbitmq_data: