services:
    php-fpm:
        container_name: market_php-fpm
        build:
            context: ./../
            dockerfile: ./docker/php-fpm/Dockerfile
        networks:
            - market

    apache:
        container_name: apache
        build:
            context: ./../
            dockerfile: ./docker/apache/Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - php-fpm
        volumes:
            - ..:/var/www:rw
        networks:
            - market

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 'admin'
        ports:
            - "3306:3306"
        networks:
            - market

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/data
        networks:
            - market

networks:
    market:

volumes:
    db-data:
    rabbitmq_data: