home:
  path: /
  controller: App\Controller\HomeController::show

# user
user_login:
  path: /login
  controller: App\Controller\LoginController::login

user_logout:
  path: /logout
  controller: App\Controller\LoginController::logout

user_register:
  path: /register
  controller: App\Controller\RegistrationController::register

# category
category_list:
  path: /category/list
  controller: App\Controller\CategoryController::show

category_delete:
  path: /category/delete/{id}
  controller: App\Controller\CategoryController::delete

category_create:
  path: /category
  controller: App\Controller\CategoryController::store

category_update:
  path: /category/{slug}
  controller: App\Controller\CategoryController::store

# product
product_list:
  path: /product/list
  controller: App\Controller\ProductController::showAll

product_list_category:
  path: /product/list/{category}
  controller: App\Controller\ProductController::showAll

product_create:
  path: /product/store
  controller: App\Controller\ProductController::store

product_update:
  path: /product/store/{slug}
  controller: App\Controller\ProductController::store

product_import:
  path: /product/import
  controller: App\Controller\ProductController::import

product_delete:
  path: /product/delete/{id}
  controller: App\Controller\ProductController::delete

product:
  path: /product/{slug}
  controller: App\Controller\ProductController::show

# api
api_get_product:
  path: /api/product/{id}
  controller: App\Controller\Api\ProductController::getProduct

api_login:
  path: /api/login
  controller: App\Controller\Api\LoginController::index
  methods: POST
