home:
  path: /
  controller: App\Controller\HomeController::show

# user
user_login:
  path: /login
  controller: App\Controller\LoginController::login

user_logout:
  path: /logout
  controller: App\Controller\LoginController::logout

user_register:
  path: /register
  controller: App\Controller\RegistrationController::register

# api
api_get_product:
  path: /api/product/{id}
  controller: App\Controller\Api\ProductController::getProduct

api_login:
  path: /api/login
  controller: App\Controller\Api\LoginController::index
  methods: POST

# category
category_list:
  path: /category/list
  controller: App\Controller\CategoryController::show

category_delete:
  path: /category/delete/{id}
  controller: App\Controller\CategoryController::delete

category_create:
  path: /category
  controller: App\Controller\CategoryController::store

category_update:
  path: /category/{slug}
  controller: App\Controller\CategoryController::store

# product
product_list:
  path: /product/list
  controller: App\Controller\ProductController::showAll

product_list_category:
  path: /product/list/{category}
  controller: App\Controller\ProductController::showAll

product_create:
  path: /product/store
  controller: App\Controller\ProductController::store

product_update:
  path: /product/store/{slug}
  controller: App\Controller\ProductController::store

product_delete:
  path: /product/delete/{id}
  controller: App\Controller\ProductController::delete

product:
  path: /product/{slug}
  controller: App\Controller\ProductController::show

# import
import:
  path: /import
  controller: App\Controller\ImportController::import

reimport:
  path: /reimport/{slug}
  controller: App\Controller\ImportController::reimport

import_edit:
  path: /import/edit/{slug}
  controller: App\Controller\ImportController::edit

import_delete:
  path: /import/delete/{slug}
  controller: App\Controller\ImportController::delete

# cart
cart:
  path: /cart
  controller: App\Controller\CartController::show

cart_add:
  path: /cart/add/{id}
  controller: App\Controller\CartController::add
  methods: POST

cart_delete:
  path: /cart/delete/{id}
  controller: App\Controller\CartController::delete
  methods: POST

cart_remove:
  path: /cart/remove/{id}
  controller: App\Controller\CartController::remove
  methods: GET|POST

# order
orders:
  path: /orders
  controller: App\Controller\OrderController::showAll

order_create:
  path: /order/create
  controller: App\Controller\OrderController::create

order_delete:
  path: /order/delete/{id}
  controller: App\Controller\OrderController::delete

order:
  path: /order/{id}
  controller: App\Controller\OrderController::show

# payment
payment_checkout:
  path: /payment/checkout
  controller: App\Controller\PaymentController::paymentCheckout
  methods: POST

payment_return:
  path: /payment/return
  controller: App\Controller\PaymentController::paymentReturn